export const workspaceName = (workspace: string) => {
  const trimmed = workspace.replace(/\/+$/, '')
  if (!trimmed) return workspace
  const parts = trimmed.split('/')
  return parts[parts.length - 1] || workspace
}

export const generatedSkillsText = (list: { enabled: boolean; skills: { name: string; reason: string; run_id: string; owned: boolean }[] }) => {
  if (!list.enabled) return 'Reflection is turned off.'
  if (list.skills.length === 0) return 'No skills generated by reflection.'
  const lines = list.skills.map(
    (skill) =>
      `- ${skill.name}${skill.owned ? '' : ' [edited or missing: reflection no longer owns it]'}: ${skill.reason} (run ${skill.run_id})`,
  )
  return ['Skills generated by reflection:', ...lines].join('\n')
}

export const sessionLabel = (id: string) => `#${id.slice(0, 8)}`

export const sendHint = (isMac = navigator.platform.toLowerCase().includes('mac')) =>
  isMac ? 'Enter send · Shift+Enter newline · ⌘V paste image' : 'Enter send · Shift+Enter newline · Ctrl+V paste image'

export const mcpServerLine = (server: { name: string; transport: string; protocol_version: string | null; state: string; tools: number; error: string | null }) => {
  const detail = server.state === 'connected' ? ` (${server.tools} tools)` : server.error ? `: ${server.error}` : ''
  const login = server.state === 'needs_login' ? ` - run: otto mcp login ${server.name}` : ''
  return `${server.name}: ${server.state}${detail} (${server.transport}, ${server.protocol_version ?? '-'})${login}`
}
